### ISSUE TITLE
Actor Tests

### ISSUE THREAD

**Issue by jarradh** [opennars/opennars2#11]
We need to find a way to test the individual actors message I/O

**Comment by jarradh** [comment]
https://github.com/puniverse/pulsar/blob/master/src/test/clojure/co/paralleluniverse/pulsar/actors_test.clj

**Comment by mfpi** [comment]
The actors have a lot of duplicate code regarding message handling, initialization and shutdown. I saw that the [`defactor`](https://github.com/opennars/opennars2/blob/master/src/narjure/actor/utils.clj) macro already exists, but it is unused.

Are there any plans to abstract the individual actors, so that the message handling can be tested only once? (Maybe add message specifications?) Then the messaging can be tested once, and each actor can have tests specific to them.

See #22 for basic actor tests for the task-creator.

**Comment by patham9** [comment]
Might be relevant in in the future: https://github.com/mfpi/opennars2/blob/56263948d39666bfbe3afc98d04016ddf6affcb8/src/narjure/actor/test_utils.clj

**Comment by patham9** [comment]
Lense is effectively what replaced actor-tests for us and made finding issues in a constantly changing design as we had in the development process easy without any maintenance cost when changes happened. As the design for the 2.0.x versions is stable actor tests could now be added, however they are now unnecessary as the actors work perfectly, thus closed.
