### ISSUE TITLE
Bag rmoving unrelated elements on add-element

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars2#37]
See this gist for details: https://gist.github.com/TonyLo1/3a461e5e4fd8a3e675298d3a22de59ad

Summary, on full bag adding elements with existing :id causes unrelated elements to be removed. For example adding :id 0 with new :priority causes :id 0 to be updated but :id 2 to be removed (see gist)

**Comment by patham9** [comment]
There is an exists? function. If when this one returns true, update-element is called, and if false, add-element as usual, the issue does not arise. To not have this logic at caller side, I suggest adding this check in add-element itself.

**Comment by patham9** [comment]
For completeness, the behavior can be explained by this:

At the stage of adding the new element of existing ID, the bag is full. Which means add-element triggers popping an element:
It removes one element of the list of lowest priority elements (which are multiple because all have 0.1 priority),
in this case it removes the id 4 element which is fine, and adds the new element  of existing ID ( (add-element bag' element) ).
So there is no issue so far at all, having element with ID 4 removes is perfectly fine.

The real issue now is that we end up with a not sorted priority-index, and this is because now the following happens:
priority-index' (conj priority-index (el id priority))
This does not update the order of the existing ID instead it just overwrites its priority.

So two possible solutions are:
1. Always update the bag according to the ID of the added element, which is expensive.
2. Apply the exists check in adding as suggested before, which is cheap and will only apply the needed disaccociation+association as demanded for getting re-sorted when really needed.
3. Only use the exists check + diassociation+association part of update-element additionally in add-element as my commit suggests.

Commit f13c24b5667469fa64b6e7efee721748ff918e21 fixes this issue by using 3.

**Comment by patham9** [comment]
Related pull request: https://github.com/opennars/opennars2/pull/38
Will close the issue when this one has be merged.
