### ISSUE TITLE
question answering is sensitive to order of premises in similarity

### ISSUE THREAD

**Issue by TonyLo1** [opennars/opennars2#51]
Works:
`<swan --> swimmer>. %0.9;0.9%
<swan --> bird>.
<swimmer <-> bird>?`

Doesn't work:
`<swan --> swimmer>. %0.9;0.9%
<swan --> bird>.
<bird <-> swimmer>?`

**Comment by patham9** [comment]
holds for all commutative terms currently, only in inference they are permuted to make sure that all conclusions are reached, but only the normalized result determines the concept where they go in so that there won't be multiple. Will fix it by normalizing the term after parsing also when I have time.

**Comment by patham9** [comment]
will be closed after my next pull request is merged.
